name: build
on:
  push:
    branches:
    - master
    - v*
    tags:
    - v*
  pull_request:
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Build binaries
    - name: Run ci
      run: make ci

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries_artifact
        path: ./bin/*

  build_push_image:
    name: Build and push images
    runs-on: ubuntu-latest
    needs: build
    if: ${{ startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: read
      id-token: write # for reading credential https://github.com/rancher-eio/read-vault-secrets
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: binaries_artifact
        path: ./bin/

    - name: Add executable permission
      run: |
        chmod +x ./bin/*

    - name: Copy binaries to package
      run: |
        cp -r ./bin/* ./package/

    - name: Read Secrets
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/harvester/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/harvester/credentials password | DOCKER_PASSWORD

    # For multi-platform support
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Declare branch
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    # rancher/terraform-provider-harvester image
    - name: docker-publish
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: rancher/terraform-provider-harvester:${{ env.branch }}-head
        file: package/Dockerfile

    - name: docker-publish-with-tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: package/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: rancher/terraform-provider-harvester:${{ github.ref_name }}
        file: package/Dockerfile
        build-args: |
          VERSION=${{ github.ref_name }}
